### ISSUE TITLE
Does the argocd-vault-plugin only support the KV secret engine?

### ISSUE THREAD

**Issue by SharifiFaranak** [argoproj-labs/argocd-vault-plugin#270]
I am able to use the avp successfully to retrieve secrets with the kv secret engine, for example a secret with path `kv/data/mysecret` is retrieved successfully. 
However, if I try to retrieve a secret from a dynamic secret engine, for example a secret with path `database-name/static-creds/role-name`, I get an error saying `Could not get secret from Vault, check that kv-v2 is the correct engine`. When I try the same path with vault-agent, I am able to get the secret written to the file successfully (so I don't think my path is wrong).

Would appreciate any insight, thanks!

**Comment by jkayani** [comment]
@SharifiFaranak Hi, yes, as it stands secret engines other than KV-V1 and KV-V2 are not supported. Looking at the docs https://www.vaultproject.io/docs/secrets/databases#usage it doesn't seem like it'd terribly hard to support, since it looks pretty similar to the `username_password` type credential IBM Cloud SM supports (and we support). Feel free to raise a PR to add this!
