### ISSUE TITLE
Support additional AppRole paths

### ISSUE THREAD

**Issue by flassagn** [argoproj-labs/argocd-vault-plugin#272]
Right now, `argocd-vault-plugin` is only able to connect on **AppRole** default path `approle` as you can see [approle.go](https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/pkg/auth/vault/approle.go#L30). 

You already solve this issue with **Kubernetes** backend.

I would like to be able to use additional **AppRole** backend paths. We can forward the path with an `AVP_APPROLE_MOUNT_PATH` env var, like you do with Kubernetes backend. Or maybe rename `AVP_K8s_MOUNT_PATH` to `AVP_MOUNT_PATH` to be use with all vault's backend.

**Comment by jkayani** [comment]
> Or maybe rename AVP_K8s_MOUNT_PATH to AVP_MOUNT_PATH to be use with all vault's backend.

Sounds like a great idea (though for backwards compatibility we'd keep both). 

To do that, I think you'd just have to make sure `auth/approle/login` is the default like is done here https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/pkg/auth/vault/kubernetes.go#L52 and modify the approle struct/constructor to accept the mount path (and use it) that would be given here: https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/pkg/config/config.go#L79 from the Viper config. 

The above is probably also worth doing for the github auth method: https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/pkg/auth/vault/github.go#L28

To keep the backwards compatibility you'd also have to modify https://github.com/argoproj-labs/argocd-vault-plugin/blob/main/pkg/config/config.go#L93 to use `AVP_MOUNT_PATH` if set, otherwise `AVP_K8s_MOUNT_PATH`. 

Feel free to open a PR for this.

**Comment by werne2j** [comment]
This feature has been release with https://github.com/argoproj-labs/argocd-vault-plugin/releases/tag/v1.8.0
