### ISSUE TITLE
Does argocd-vault-plugin supports/work with vault namespaces ?

### ISSUE THREAD

**Issue by davshafik** [argoproj-labs/argocd-vault-plugin#274]
Does argocd-vault-plugin supports vault namespaces,  e.g if i create namespaces in vault setup and i want to retrieve the secretes from different vault namespace. 
is it supported or going to be supported later/soon ?

**Comment by jkayani** [comment]
https://www.vaultproject.io/docs/enterprise/namespaces#usage

I personally haven't tried it since I haven't used "Vault Enterprise" but it says you can send API requests to the right namespace either by header (which unless there is a `VAULT_*` env variable you can pass to the Vault SDK to set that header's value for all requests, AVP won't do) _or_ by just putting it in the path: `ns1/secret/foo`. I think it's worth a try (have a k8s secret with a placeholder like `<path:your-namespace/secret/a-secret-in-the-vault#a-key-in-that-secret>`

**Comment by werne2j** [comment]
@davshafik This issue should add a little more insight https://github.com/argoproj-labs/argocd-vault-plugin/issues/219. All Vault env vars, namespace included are supported by adding them to the repo-server.

**Comment by jkayani** [comment]
https://www.vaultproject.io/docs/commands#vault_namespace

Thanks @werne2j
