### ISSUE TITLE
v1.9.0 does not seem to be able to handle AWS Secret Manager secrets that are not KV (i.e. Plaintext)

### ISSUE THREAD

**Issue by sinkr** [argoproj-labs/argocd-vault-plugin#308]
**Describe the bug**
Cannot render secrets stored in AWS Secret Manager as type Plaintext (versus as JSON key/value), like so:

```
aws secretsmanager get-secret-value  --secret-id My-Secret-Plaintext                                 
{
    "ARN": "arn:aws:secretsmanager:us-west-2:redacted:secret:My-Secret-Plaintext-vmapi",
    "Name": "My-Secret-Plaintext",
    "VersionId": "<REDACTED>",
    "SecretString": "myusefulinfohere",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": "2022-02-21T14:10:10.332000-05:00"
}
```

**To Reproduce**
Simple expansion YAML (numerous iterations attempted, including annotation-style):
```
kind: Secret
apiVersion: v1
metadata:
  info: <path:My-Secret-Plaintext#My-Secret-Plaintext>
```

**Expected behavior**
The SecretString, _myusefulinfohere_ should be rendered.

**Screenshots**
Usage and error given:
```
./argocd-vault-plugin generate -s argocd-vault-plugin-credentials ./test.yaml
Error: Replace: could not replace all placeholders in Template:
invalid character 'c' after top-level `value`
```

**Comment by jkayani** [comment]
I think you're running into the same issue reported here: https://github.com/argoproj-labs/argocd-vault-plugin/pull/182 - your secret string isn't JSON and therefore it can't be unmarshalled into a map, thus the cryptic error message. 

At that the time we didn't accept that PR because we wanted to solve the problem in a better way. Not sure if @werne2j has had a change of thoughts since then. You can work around this by putting your secret into a JSON string and extracting the key you need with the `jsonPath` modifier, something like this: `<path:My-Secret-Plaintext#My-Secret-Plaintext | jsonPath {.key-with-plain-value-you-need}`

**Comment by sinkr** [comment]
Ah yes, my mistake and apologies for opening a separate thread.

**Comment by barryib** [comment]
I think we should reopen this issue. Actually Secret Manager support secrets as plaintext. Some applications expects to have plaintext secrets and converting them into key/value is not an option since it'll break those apps.

@jkayani @werne2j @mms-gianni please advise.

**Comment by mms-gianni** [comment]
@barryib THX for mentioning. We moved away from vault-plugin to [external secrets](https://external-secrets.io/latest/) because of this issue. 

I'd still promote my PR as a simple and clean solution for this problem.

**Comment by barryib** [comment]
Thanks @mms-gianni for your feedback. In our case, it's not possible for a particular use case to move to external secret because external secret support only secrets objects and [not custom objects](https://github.com/external-secrets/external-secrets/pull/3449), while we do want to inject some parameters in CRD. This is why we can't for now move off avp.

In that way, Is it possible to reopen https://github.com/argoproj-labs/argocd-vault-plugin/pull/182 ?
