### ISSUE TITLE
Documentation for VAULT_CACERT, VAULT_CAPATH and VAULT_SKIP_VERIFY is missing

### ISSUE THREAD

**Issue by stehnes** [argoproj-labs/argocd-vault-plugin#312]
In release 0.5.0 this was added:

* feat: Add support for cacert, capath and skip verify variables by @werne2j in https://github.com/argoproj-labs/argocd-vault-plugin/pull/78

At that time, it was documented in README.md
| Name            | Description                | Notes                |
| --------------- | ----------- | ----- |
| VAULT_CACERT | CACert is the path to a PEM-encoded CA cert file to use to verify the Vault server SSL certificate      | In order to use, you must create a secret with the certificate you want to load, and then mount that secret on the argocd-repo-server deployment. Then you can set this path to the mount point of the secret.                |
| VAULT_CAPATH | CAPath is the path to a directory of PEM-encoded CA cert files to verify the Vault server SSL certificate.      | In order to use, you must create a secret with the certificate(s) you want to load, and then mount that secret on the argocd-repo-server deployment. Then you can set this path to the mount point of the secret.                 |
| VAULT_SKIP_VERIFY | Enables or disables SSL verification      | Optional                 |

<br>

**Expected behavior**
This information does not exist in the current documentation (Release 1.9.0)

**Comment by werne2j** [comment]
@stehnes that is because we moved away from wrapping specific environment variables and to supporting all backend environment variables https://github.com/argoproj-labs/argocd-vault-plugin/issues/85 it does appear we need to add something here https://argocd-vault-plugin.readthedocs.io/en/stable/backends/#hashicorp-vault to show that better.

You can view the Vault Env Var documentation here https://www.vaultproject.io/docs/commands#environment-variables all of which are supported
